task-2: first-check
charleswein/tms-react pull request #2
Opened 2020-09-14 11:35 UTC by charleswein

first-test

2020-09-15 12:52 UTC, lipskiy-aleh commented on index.js
> +IntBuilder.random = function (min, max) {
Не верный метод рандом. 
Если он статический то он никак не должен работать с this.
IntBuilder.random(1, 100) он должен вот так вот вызываться без каки-либо new

2020-09-15 12:53 UTC, lipskiy-aleh requested changes
Оба класса должны иметь общего родителя. И от него наследоваться. 
Те у тебя должно быть только три класса IntBuilder, StrBuilder, Builder

2020-09-15 15:22 UTC, charleswein reviewed
Исправил надеюсь что верно...)

2020-09-15 15:22 UTC, charleswein commented on index.js
> +IntBuilder.random = function (min, max) {
исправил вроде как)

2020-09-17 07:02 UTC, lipskiy-aleh commented on index.js
> +  var sumElemArr = [...args].reduce((result, elem) => {
[...args] - вот это лишняя операция, дочтаточно просто написать args.reduce

2020-09-17 07:03 UTC, lipskiy-aleh commented on index.js
> +  var sumElemArr = [...args].reduce((result, elem) => {
Как вариант вот этот редьюс можно вынести в отдельный метод и его заюзать и в ф-ции plus и minus

2020-09-17 07:04 UTC, lipskiy-aleh commented on index.js
> +    this.num = num;
Зачем тут две отдельные переменные ? 
Правильнее будет юзать this.value и присылать значение а какой у него тип не важно

2020-09-17 07:06 UTC, lipskiy-aleh commented on index.js
> +  Builder.constructor.call(this);
Когда ты вызвал конструктор родителя, то  тебе уже не надо присваивать значение дальше, эт должно произойти в конструкторе родителям иначе какой вообще смысл наследования которое у тебя написано ?

2020-09-17 07:07 UTC, lipskiy-aleh commented on index.js
> +    this.str = str;
Тоже самое, ты ведь вызвал уже родителям и он проинициализировал твой this.str зачем ты его переопределяешь дальше ?

2020-09-17 07:07 UTC, lipskiy-aleh commented on index.js
> +    var sumElemArr = [...args].reduce((result, elem) => {
[...args] -> args.reduce

2020-09-17 07:08 UTC, lipskiy-aleh commented
Ну и в папку перенести все файлы которые относятся к заданию

2020-09-17 11:06 UTC, merged